title: Yashyasvi Agarwal
logo: https://media-exp1.licdn.com/dms/image/C5603AQHQVr7pFrRuEg/profile-displayphoto-shrink_800_800/0/1588519982536?e=1658966400&v=beta&t=xGvn2fsfTWOw_A64lnOpembuw14BovpOSByeYiET8BM
description: Software Engineer at Microsoft
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
